# Generated by Django 5.2.6 on 2025-09-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formateur',
            options={},
        ),
    ]
