# Generated by Django 5.2.6 on 2025-09-24 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duree', models.IntegerField(help_text='Durée en heures')),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='formateur.formateur')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('salle', models.CharField(max_length=100)),
                ('places_max', models.IntegerField()),
                ('places_restantes', models.IntegerField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En Cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='param.cours')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_formateur', to='formateur.formateur')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
    ]
