# Generated by Django 5.2.6 on 2025-09-26 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentis', '0001_initial'),
        ('param', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('carte', 'Carte bancaire')], default='especes', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='apprentis.inscription')),
            ],
        ),
    ]
