# Generated by Django 5.2.6 on 2025-09-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
    ]
