# Generated by Django 5.2.6 on 2025-09-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0002_alter_session_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nb_apprentis_max', models.PositiveIntegerField()),
                ('actif', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('duree', models.CharField(help_text='Ex: 2 jours, 10h', max_length=100)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='param.packformation')),
            ],
        ),
    ]
