# Generated by Django 5.2.6 on 2025-09-24 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('param', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apprenti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apprenti',
                'verbose_name_plural': 'Apprentis',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('attente', 'En Attente'), ('annule', 'Annulé')], default='inscrit', max_length=20)),
                ('apprenti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='apprentis.apprenti')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='param.session')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'unique_together': {('apprenti', 'session')},
            },
        ),
    ]
