# Generated by Django 5.2.6 on 2025-09-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('param', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(default='migrations@exemple.com', max_length=254, unique=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('apprenti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='apprentis.apprenti')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='param.packformation')),
            ],
            options={
                'unique_together': {('apprenti', 'pack')},
            },
        ),
    ]
